# Generated by Django 6.0.1 on 2026-01-08 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'indicator_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('crypto_symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('market', models.CharField(blank=True, max_length=100, null=True)),
                ('locale', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_usd_pair', models.BooleanField(default=False)),
                ('currency_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('currency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('base_currency_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('base_currency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('last_trade_timestamp', models.FloatField(blank=True, null=True)),
                ('last_updated', models.CharField(blank=True, max_length=100, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tickers',
                'ordering': ['-market_cap', 'ticker'],
            },
        ),
        migrations.CreateModel(
            name='GlobalLiquidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_id', models.CharField(db_index=True, max_length=50)),
                ('series_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(db_index=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('collected_at', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'global_liquidity',
                'ordering': ['date'],
                'unique_together': {('series_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True)),
                ('indicator_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.indicatortype')),
            ],
            options={
                'db_table': 'indicators',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('value', models.FloatField()),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=100, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_data', to='main.indicator')),
            ],
            options={
                'db_table': 'indicator_data',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['indicator', 'date'], name='indicator_d_indicat_791310_idx')],
                'unique_together': {('indicator', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TickerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('vwap', models.FloatField(blank=True, null=True)),
                ('transactions', models.IntegerField(blank=True, null=True)),
                ('collected_at', models.CharField(blank=True, max_length=100, null=True)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_data', to='main.ticker')),
            ],
            options={
                'db_table': 'ticker_data',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='ticker_data_ticker__2cf7af_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
