# Generated by Django 6.0.1 on 2026-01-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='auto_update',
            field=models.BooleanField(default=False, help_text='Automatically update this indicator using the calculator class'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='calculator_class',
            field=models.CharField(blank=True, help_text='Python module path to calculator class (e.g., indicators.calculators.RSICalculator)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='calculator_config',
            field=models.JSONField(blank=True, help_text='JSON configuration for the calculator class', null=True),
        ),
    ]
