# Generated by Django 6.0.1 on 2026-01-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_indicator_auto_update_indicator_calculator_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='calculation_type',
            field=models.CharField(choices=[('custom', 'Custom Calculator'), ('stock_indicator', 'Stock-Indicators Package')], default='custom', help_text='Type of calculator to use', max_length=20),
        ),
        migrations.AddField(
            model_name='indicator',
            name='stock_indicator_name',
            field=models.CharField(blank=True, help_text='Name of indicator from stock-indicators package (e.g., rsi, macd, sma)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='stock_indicator_settings',
            field=models.JSONField(blank=True, help_text='Settings for the stock-indicators calculator', null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='stock_indicator_settings_class',
            field=models.CharField(blank=True, help_text='Python module path to settings class (e.g., main.indicators.settings.RSISettings)', max_length=500, null=True),
        ),
    ]
